import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
  title: "Studily",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],  // Optional: Choose the font subset(s) you need
  weight: ["200", "400", "500", "700", "800", "900"],  // Optional: Choose specific font weights you want to use
  display: "swap",  // Optional: Improves loading performance by swapping fonts
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        {children}
      </body>
    </html>
  );
}
